name: Test
on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Environment
      full:
        type: boolean
        description: Deploy ALL environments
      cloud:
        type: boolean
        description: Cloud runner (default false)
  # workflow_run:
  #   workflows: ["Pull Request Handler"]
  #   types:
  #     - completed 
  release:
    types:
      - created
  push:
    paths-ignore:
      - '**.md'
      - '.github/workflows/*.yml'
      - '.github/workflows/app.yml'     
    branches: [ 'release', 'release/*', 'feature/*' ]
  pull_request:
    branches: [ "release" ]
    types:
      - closed
    paths-ignore:
      - '**/*.md'
      - '**/*.yml'
jobs:

  Checkout:
    uses: ankgoya1/pr/.github/workflows/checkout.yml@main

  Publish:
    needs: Checkout
    uses: ankgoya1/pr/.github/workflows/publish.yml@main
    secrets:
      token: ${{ secrets.USER }}
      pass: ${{ secrets.GIT_PASS }}
    with:  
      user: Ankit
      name: ${{ vars.name }}
      mname: ${{ vars.mname }} 
  
  Build:
    runs-on: [ ubuntu-latest ]
    
    steps: 
      # - name: Update BC Version variable
      #   uses: indiesdev/curl@v1.1
      #   with:
      #     url: https://api.github.com/repos/${{ github.repository }}/actions/variables/BC_3_BUILD_VERSION
      #     headers: '{ "Authorization": "Bearer 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" }'
      #     method: "PATCH"
      #     timeout: 10000
      #     accept: 204
      #     body: '{ "name": "BC_3_BUILD_VERSION", "value": "369" }'
      #     log-response: true
      - name: Update Variable
        env:
          TOKEN: ${{ secrets.GIT_PASS }} # Access token for repo
        run: |
          curl -L \
          -X PATCH \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/ankgoya1/App1/actions/variables/BC_3_BUILD_VERSION \
          -d '{"name":"BC_3_BUILD_VERSION","value":"369"}'   
