name: Test
on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Environment
      full:
        type: boolean
        description: Deploy ALL environments
      cloud:
        type: boolean
        description: Cloud runner (default false)
  # workflow_run:
  #   workflows: ["Pull Request Handler"]
  #   types:
  #     - completed
  release:
    types:
      - created
  push:
    paths-ignore:
      - '**.md'
      - '.github/workflows/*.yaml'
      - '.github/workflows/app.yaml'
jobs:

  Checkout:
    uses: ankgoya1/pr/.github/workflows/checkout.yml@main

  Publish:
    needs: Checkout
    uses: ankgoya1/pr/.github/workflows/publish.yml@main
    secrets:
      token: ${{ secrets.USER }}
      pass: ${{ secrets.GIT_PASS }}
    with:  
      user: Ankit
      name: ${{ vars.name }}
      mname: ${{ vars.mname }}      
    branches: [ 'release', 'release/*', 'feature/*' ]
  pull_request:
    branches: [ "release" ]
    types:
      - closed
    paths-ignore:
      - '**/*.md'
      - '**/*.yaml'
