name: App1

on:
  push:
    branches:
      - main

env:
  MY_VAR: Testing

jobs:
  Variables:
    needs: [ ]
    runs-on: ubuntu-latest
    outputs:
      my_var: ${{ steps.set_output.outputs.MY_VAR }}
      user: Ankit

    steps: 
      - name: Set output variables
        id: set_output
        run: |
          echo "::set-output name=MY_VAR::${MY_VAR}"
          echo "::set-output name=USER::${USER}"

  # Print:
  #   needs: Variables
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Print Value
  #       run: |
  #         echo "value is: $MY_VAR"

  Checkout:
    uses: ankgoya1/pr/.github/workflows/checkout.yml@main

  Publish:
    needs: Checkout
    uses: ankgoya1/pr/.github/workflows/publish.yml@main
    with:
      VAR: ${{ needs.Variables.outputs.my_var }}
      USER_SECRET: ${{ secrets.USER }}
