name: App1

on:
  push:
    branches:
      - main
env:
  MY_VAR: Testing

jobs:
  Variables:
    needs: [ ]
    runs-on: ubuntu-latest
    outputs:
      my_var: ${{ steps.set_output.outputs.MY_VAR }}
      user: Ankit
      
  #   steps: 
  #     # - name: Checkout code
  #     #   uses: actions/checkout@v2
  #     - name: Set output variables
  #       id: set_output
  #       run: |
  #         echo "::set-output name=my_var::${MY_VAR}"
  #         echo "::set-output name=user::${USER}"
  Print:
    needs: Variables
    runs-on: ubuntu-latest
    steps:
      - name: Print Value
        run: |
          echo "value is: $MY_VAR"

  Checkout:
    # needs: Variables
    uses: ankgoya1/pr/.github/workflows/checkout.yml@main
    
  # Build:
  #   needs: Checkout
  #   uses: ankgoya1/pr/.github/workflows/build.yml@main
  Publish:
    needs: Checkout
    uses: ankgoya1/pr/.github/workflows/publish.yml@main
    with:
      VAR: ${{ needs.Variables.outputs.my_var }}
      USER_SECRET: ${{ secrets.USER }}
