name: CI/CD Workflow

on:
  push:
    branches:
      - main

env:
  MY_VAR: Testing
  USER: ${{ secrets.USER }}
  
jobs:
  Variables:
    runs-on: ubuntu-latest
    outputs:
      my_var: ${{ steps.set_output.outputs.my_var }}
      user: ${{ steps.set_output.outputs.user }}
    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v2
      - name: Set output variables
        id: set_output
        run: |
          echo "::set-output name=my_var::${MY_VAR}"
          echo "::set-output name=user::${USER}"

  Checkout:
    needs: Variables
    uses: ankgoya1/pr/.github/workflows/checkout.yml@main
    
  Build:
    needs: Checkout
    uses: ankgoya1/pr/.github/workflows/build.yml@main

  Publish:
    needs: Build
    uses: ankgoya1/pr/.github/workflows/publish.yml@main
    with:
      MY_VAR: ${{ needs.Variables.outputs.my_var }}
      USER: ${{ needs.Variables.outputs.user }}
