name: App1

on:
  push:
    branches:
      - main

jobs:
  Variables:
    env:
      MY_VAR: Testing
    runs-on: ubuntu-latest
    outputs:
      my_var: ${{ steps.set_output.outputs.MY_VAR }}

    steps: 
      - name: Set output variables
        id: set_output
        run: |
          echo "::set-output name=MY_VAR::${MY_VAR}"
          
  Print:
    needs: Variables
    runs-on: ubuntu-latest
    steps:
      - name: Print Value
        run: |
          echo "value is : $MY_VAR"

  Checkout:
    needs: Print
    uses: ankgoya1/pr/.github/workflows/checkout.yml@main

  Publish:
    needs: Checkout
    uses: ankgoya1/pr/.github/workflows/publish.yml@main
    secrets:
      token: ${{ secrets.USER }}
      pass: ${{ secrets.GIT_PASS }}
    with:  
      my_var: ${{ env.MY_VAR }}

