name: CI/CD Workflow

on:
  push:
    branches:
      - main

env:
  MY_VAR: Testing
  USER: ${{ secrets.USER }}
  
jobs:
  Checkout:
    runs-on: ubuntu-latest
    outputs:
      my_var: ${{ env.MY_VAR }}
      user: ${{ secrets.USER }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

  Build:
    needs: Checkout
    runs-on: ubuntu-latest
    env:
      MY_VAR: ${{ needs.Checkout.outputs.my_var }}
      USER: ${{ needs.Checkout.outputs.user }}
    steps:
      - name: Run Build
        uses: ankgoya1/pr/.github/workflows/build.yml@main

  Publish:
    needs: Build
    runs-on: ubuntu-latest
    env:
      MY_VAR: ${{ needs.Checkout.outputs.my_var }}
      USER: ${{ needs.Checkout.outputs.user }}
    steps:
      - name: Run Publish
        uses: ankgoya1/pr/.github/workflows/publish.yml@main
