name: CI/CD Workflow

on:
  push:
    branches:
      - main
jobs:
  Checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

  Build:
    runs-on: ubuntu-latest
    needs: Checkout
    steps:
      - name: Build
        uses: ankgoya1/pr/.github/workflows/build.yml@main

  Publish:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Publish
        uses: ankgoya1/pr/.github/workflows/publish.yml@main
