name: App1

on:
  # push:
  #   branches:
  #     - main

  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Environment
jobs:

  Checkout:
    uses: ankgoya1/pr/.github/workflows/checkout.yml@main

  Publish:
    needs: Checkout
    uses: ankgoya1/pr/.github/workflows/publish.yml@main
    secrets:
      token: ${{ secrets.USER }}
      pass: ${{ secrets.GIT_PASS }}
    with:  
      user: Ankit
      name: ${{ vars.name }}
      mname: ${{ vars.mname }}
