name: CI/CD Workflow

on:
  push:
    branches:
      - main
env:
  MY_VAR: Testing
  USER: ${{ secrets.USER }}
  
jobs:
  Checkout:
    uses: ankgoya1/pr/.github/workflows/checkout.yml@main

  Build:
    needs: Checkout
    uses: ankgoya1/pr/.github/workflows/build.yml@main

  Publish:
    needs: Build
    uses: ankgoya1/pr/.github/workflows/publish.yml@main
